/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {

    // Required for any Java project
    id("java") 

    // For CLI apps with a main() method
    id("application") 

    // Spring Boot plugin
    id("org.springframework.boot") version "3.2.0"

    // (Optional) For dependency management
    id("io.spring.dependency-management") version "1.1.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // Spring Boot starter (core framework)
    implementation("org.springframework.boot:spring-boot-starter")

    // Optional: Additional libraries - Guava 
    implementation("com.google.guava:guava:32.1.2-jre")

    // Spring Boot test support (includes JUnit 5, Mockito, etc.)
    testImplementation("org.springframework.boot:spring-boot-starter-test")
   
   // Migrate to JUnit 5 with BOM-managed Jupiter dependencies
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")


    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.springbootuserdemo.Application"
}

// Configures JUnit 5 platform with test logging for passed/skipped/failed events
tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}